# Site settings
title:          观雨小粉丝
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://kghch.github.io"

# Author
author:
  name:         hanhan
  url:          https://kghch.github.io 
  email:        wanghan0307@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
