# Site settings
title:          九行豆角
description:    "三十而立，四十不惑，五十知天命"
baseurl:        "/"
url:            "https://kghch.github.io"

# Author
author:
  name:         hanhan
  url:          http://hhan.site
  email:        wanghan0307@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme